In [1]:
import numpy as np
import scipy as sc

In [2]:
A = np.array([[2,4,6],[5,3,2],[7,8,9]])
print(A)

[[2 4 6]
 [5 3 2]
 [7 8 9]]


In [4]:
B = np.array([[18],[13],[30]])
print(B)

[[18]
 [13]
 [30]]


In [11]:
X = sc.linalg.solve(A,B)
print(X)

[[ 4.5]
 [-7.5]
 [ 6.5]]


In [12]:
def dydx(x,y):
  return((x-y)/2)

In [19]:
def rungeKutta(x0, y0, x, h):
  n = int((x-x0)/h)
  y = y0
  for i in range(1, n+1):
    k1 = h*dydx(x0,y)
    k2 = h*dydx(x0 + 0.5*h, y+0.5*k1)
    k3 = h*dydx(x0 + 0.5*h, y+0.5*k2)
    k4 = h*dydx(x0 + h, y+k3)

    y = y + (1.0/6.0)*(k1 + 2*k2 + 2*k3 + k4)
    x0 = x0 + h
  return y


In [20]:
x0 = 0
y = 0
x = 1
h = 2
print('The value of y at x is: ', rungeKutta(x0,y,x,h))

The value of y at x is:  0


In [21]:
plt.plot(x,y)
plt.title('x versus y')
plt.xlabel('x')
plt.ylabel('y')
plt.show()


NameError: name 'plt' is not defined

In [23]:
import requests
api_url = https://api.open-meteo.com/v1/forecast?latitude=2.5&longitude=112.5&hourly=temperature_2m&timezone=Asia%2FSingapore&forecast_days=1

response = requests.get(api_url)
Singapore_forecast = response.json()

days = int(input('Enter number of days for forecast (between 1 to 16 only): '))

for Singapore_forecast:
  print(f"{"time":"iso8601","temperature_2m":"°C"}")

SyntaxError: invalid decimal literal (<ipython-input-23-5cca21dd8915>, line 2)